FROM apache/spark:4.2.0

USER root

RUN curl -L -o /opt/spark/jars/spark-sql-kafka-0-10_2.13-4.2.0.jar https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.13/4.2.0/spark-sql-kafka-0-10_2.13-4.2.0.jar

USER spark
