FROM apache/spark:4.2.0

USER root

# Removing manual JAR download to let --packages handle all transitive dependencies
# RUN curl -L -o /opt/spark/jars/spark-sql-kafka-0-10_2.13-4.2.0.jar ...

USER spark
